# Generated by Django 5.0.4 on 2024-04-08 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hilo',
            name='contenido',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hilo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 18, 31, 13, 813378)),
        ),
    ]
