# Generated by Django 5.0.4 on 2024-04-08 01:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_rename_tags_hilo_comentarios_alter_hilo_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hilo',
            name='comentarios',
        ),
        migrations.AlterField(
            model_name='hilo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 19, 0, 34, 431411)),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 4, 7, 19, 0, 34, 431411))),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.hilo')),

            ],
        ),
        migrations.AddField(
            model_name='hilo',
            name='comentarios',
            field=models.ManyToManyField(related_name='Hilo', to='foro.comentario'),
        ),
    ]
