# Generated by Django 5.0.4 on 2024-04-08 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_remove_hilo_comentarios_alter_hilo_fecha_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 19, 32, 29, 884205)),
        ),
        migrations.AlterField(
            model_name='hilo',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hilo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 19, 32, 29, 884205)),
        ),
    ]
