# Generated by Django 5.0.4 on 2024-04-08 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0005_alter_comentario_fecha_creacion_alter_hilo_contenido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hilo',
            name='comentarios',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 23, 4, 6, 450638)),
        ),
        migrations.AlterField(
            model_name='hilo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 23, 4, 6, 450638)),
        ),
    ]
