# Generated by Django 5.0.4 on 2024-04-13 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0009_alter_comentario_fecha_creacion_alter_hilo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 15, 34, 4, 198202)),
        ),
        migrations.AlterField(
            model_name='hilo',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 15, 34, 4, 197202)),
        ),
    ]
