# Generated by Django 5.0.4 on 2024-04-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='matricula',
            field=models.IntegerField(default=0),
        ),
    ]
