# Generated by Django 5.0.4 on 2024-04-08 23:19

import apps.user.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraccount_groups_useraccount_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_de_entrada',
            field=models.DateField(default=datetime.date(2024, 4, 8)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='foto',
            field=models.ImageField(default='static/default/foto_default/cuenta.png', upload_to=apps.user.models.path_dir_perfil),
        ),
    ]
