# Generated by Django 5.0.4 on 2024-04-18 22:37

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_seguidor_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguidor',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 16, 37, 6, 850511)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_de_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_de_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
