# Generated by Django 5.0.4 on 2024-04-18 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_seguidor_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguidor',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 17, 22, 37, 889439)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_de_entrada',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 17, 22, 37, 886435)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_de_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 4, 18, 17, 22, 37, 886435)),
        ),
    ]
