# Generated by Django 5.0.4 on 2024-04-08 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_subido_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subido',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 23, 13, 22, 922730)),
        ),
    ]
