# Generated by Django 5.0.4 on 2024-04-19 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_comentarios_fecha_alter_dislike_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 33, 53, 635825)),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 33, 53, 634841)),
        ),
        migrations.AlterField(
            model_name='dislikeacomentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 33, 53, 636849)),
        ),
        migrations.AlterField(
            model_name='dislikearespuestaalcomentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 33, 53, 637823)),
        ),
        migrations.AlterField(
            model_name='like',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 33, 53, 634841)),
        ),
        migrations.AlterField(
            model_name='likeacomentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 33, 53, 635825)),
        ),
        migrations.AlterField(
            model_name='likearespuestaalcomentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 33, 53, 636849)),
        ),
        migrations.AlterField(
            model_name='post',
            name='subido',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 33, 53, 633822)),
        ),
        migrations.AlterField(
            model_name='respuestaacomentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 33, 53, 636849)),
        ),
        migrations.AlterField(
            model_name='vistas',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 33, 53, 637823)),
        ),
    ]
