export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SINGUP_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_SUCCESS';

export const ACTIVACION_SUCCESS = 'ACTIVACION_SUCCESS';
export const ACTIVACION_FAIL = 'ACTIVACION_FAIL';

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';

export const LOGOUT = 'LOGOUT';

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const GET_PAGINA_DE_USUARIO_SUCCESS = 'GET_PAGINA_DE_USUARIO_SUCCESS';
export const GET_PAGINA_DE_USUARIO_FAIL = 'GET_PAGINA_DE_USUARIO_FAIL';

export const GET_GALERIA_DE_USUARIO_SUCCESS = 'GET_GALERIA_DE_USUARIO_SUCCESS';
export const GET_GALERIA_DE_USUARIO_FAIL = 'GET_GALERIA_DE_USUARIO_FAIL';

export const GET_FORO_SUCCESS = 'GET_FORO_SUCCESS';
export const GET_FORO_FAIL = 'GET_FORO_FAIL';

export const GET_COMENTARIOS_SUCCESS = 'GET_COMENTARIOS_SUCCESS';
export const GET_COMENTARIOS_FAIL = 'GET_COMENTARIOS_FAIL';

export const GET_MI_PAGINA_SUCCESS = 'GET_MI_PAGINA_SUCCESS';
export const GET_MI_PAGINA_FAIL = 'GET_MI_PAGINA_FAIL';

export const GET_HILO_SUCCESS = 'GET_HILO_SUCCESS';
export const GET_HILO_FAIL = 'GET_HILO_FAIL'; 

export const GET_DISCUSION_SUCCESS = 'GET_DISCUSION_SUCCESS';
export const GET_DISCUSION_FAIL = 'GET_DISCUSION_FAIL';

export const GET_RESPUESTAS_DISCUCION_SUCCESS = 'GET_RESPUESTAS_DISCUCION_SUCCESS';
export const GET_RESPUESTAS_DISCUCION_FAIL = 'GET_RESPUESTAS_DISCUCION_FAIL';

export const GET_POST_CON_TAG_SUCCESS = 'GET_POST_CON_TAG_SUCCESS';
export const GET_POST_CON_TAG_FAIL = 'GET_POST_CON_TAG_FAIL';

export const GET_LIKES_Y_DISLIKES_SUCCESS = 'GET_LIKES_Y_DISLIKES_SUCCESS';
export const GET_LIKES_Y_DISLIKES_FAIL = 'GET_LIKES_Y_DISLIKES_FAIL';

export const GET_POST_PREVIEW_SUCCESS = 'GET_POST_PREVIEW_SUCCESS';
export const GET_POST_PREVIEW_FAIL = 'GET_POST_PREVIEW_FAIL';