# Generated by Django 5.0.4 on 2024-04-17 01:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discusion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='likes',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 19, 26, 49, 855290)),
        ),
        migrations.AlterField(
            model_name='respuestasaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 19, 26, 49, 857291)),
        ),
        migrations.CreateModel(
            name='DislikeAOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 4, 16, 19, 26, 49, 856288))),
                ('a_la_opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discusion.opinion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DislikeARespuestaAOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 4, 16, 19, 26, 49, 858292))),
                ('a_la_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discusion.respuestasaopinion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeAOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 4, 16, 19, 26, 49, 855290))),
                ('a_la_opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discusion.opinion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeARespuestaAOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 4, 16, 19, 26, 49, 858292))),
                ('a_la_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discusion.respuestasaopinion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
