# Generated by Django 5.0.4 on 2024-04-18 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discusion', '0003_alter_dislikeaopinion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikeaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 16, 37, 6, 861513)),
        ),
        migrations.AlterField(
            model_name='dislikearespuestaaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 16, 37, 6, 862513)),
        ),
        migrations.AlterField(
            model_name='likeaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 16, 37, 6, 861513)),
        ),
        migrations.AlterField(
            model_name='likearespuestaaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 16, 37, 6, 862513)),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 16, 37, 6, 860513)),
        ),
        migrations.AlterField(
            model_name='respuestasaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 16, 37, 6, 862513)),
        ),
    ]
