# Generated by Django 5.0.4 on 2024-04-18 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discusion', '0004_alter_dislikeaopinion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikeaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 17, 22, 37, 899436)),
        ),
        migrations.AlterField(
            model_name='dislikearespuestaaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 17, 22, 37, 900436)),
        ),
        migrations.AlterField(
            model_name='likeaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 17, 22, 37, 899436)),
        ),
        migrations.AlterField(
            model_name='likearespuestaaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 17, 22, 37, 900436)),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 17, 22, 37, 898436)),
        ),
        migrations.AlterField(
            model_name='respuestasaopinion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 17, 22, 37, 899436)),
        ),
    ]
